language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

install: true

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic

bench:
  go test -bench=.

after_success:
  - bash <(curl -s https://codecov.io/bash)
