language: go

notifications:
  email:
    recipients:
      - edercosta94@live.com
    on_success: never
    on_failure: always

go:
  - 1.12.x

before_install:
  - go get -t -v ./...

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)